---
title: "Teaching"
description: "Courses at the Department of Economics, University of Oregon. Expand a course for its description."
---

## Undergraduate

:::: {.paper}
### EC 201: Principles of Microeconomics

[[Sample syllabus](assets/pdf/ec201-sample-syllabus.pdf)]{.paper-links}

::: {.callout-note appearance="simple" collapse="true" icon="false"}
## Course description
Economics is the study of constrained decision making, or, how individuals, organizations, governments, and societies allocate scarce resources and respond to incentives. Microeconomics is the study of decisions made by relatively "small" actors: individuals, firms, and local governments. This introductory-level course provides students with an overview of important concepts in microeconomics and builds a foundation for studying issues in a variety of topic areas, including labor, trade, environmental policy, industrial organization, and others. Along the way, students apply the "economist's toolkit" to national and international policy questions including climate change, intellectual property protection, arms control, and discrimination.

The course begins with a simple model of markets based on the idea that consumers and suppliers wish to trade goods for money. Students use this model to explore the impact of government policy on outcomes in real-world markets. The course then dives deeper into the drivers of decision making and explores different types of competition before exposing students to game theory, the market for labor, and the problems posed by imperfect information. The course ends with a specialized topic chosen each term by students.
:::
::::

:::: {.paper}
### EC 410/510 (Experimental course code): The Economics of Power

[[Sample syllabus](assets/pdf/ec410-sample-syllabus-econ-of-power.pdf)]{.paper-links}

::: {.callout-note appearance="simple" collapse="true" icon="false"}
## Course description
Often our choices are constrained or influenced by the power that others wield over us. Whether it’s the power of a large social media corporation to determine what constitutes acceptable content for their platform, the power of a manager to fire employees at will, or the power of the primary earner in a marriage to compel their partner to endure mistreatment, systems of power pervade our experience of ourselves, each other, and the world around us. Where does power come from? How is it wielded? How should we live in a world filled with giants? This course will attempt to answer these questions through the lens of economic analysis, both theoretical and empirical. In the first half of the course we will discuss power systems at scales ranging from interpersonal to international. The second half of the course will feature an ongoing simulation based on real-world power struggles.
:::
::::

:::: {.paper}
### EC 460/560: Theories of Industrial Organization

[[Sample syllabus](assets/pdf/ec460-sample-syllabus.pdf)]{.paper-links}

::: {.callout-note appearance="simple" collapse="true" icon="false"}
## Course description
Industrial organization is the study of the behaviors of firms and consumers in individual markets. This advanced undergraduate field course covers the theory of industrial organization and includes quantitative measures and institutional descriptions of American and global industry. The course emphasizes the determinants and consequences of market power.

The course begins with a review of consumer and producer theory with a focus on non-strategic (i.e. monopolist) pricing policies. Students then learn to use game theory to explore static and dynamic models of oligopoly. The course then zooms out to consider the determinants of industry structure, including technology, demand, mergers and acquisitions, and firm strategies designed to deter entry. Students then learn ways to conceptualize other common features of imperfectly competitive markets, including vertical relationships, product differentiation, and network effects. The course ends with an overview of current research methods, results, and open questions in the field.
:::
::::

## Graduate

:::: {.paper}
### EC 607: Seminar in Industrial Organization: Structural Methods and Applications

[[Sample syllabus](assets/pdf/ec607-sample-syllabus.pdf)]{.paper-links}

::: {.callout-note appearance="simple" collapse="true" icon="false"}
## Course description
Over the past 25 years, the study of industrial organization (IO) has been transformed by the introduction of computationally tractable structural models: models in which restrictive assumptions are made about market participants and the form of their interaction. While the assumptions are, at times, strong, they have allowed the field to make significant progress on empirical questions and more precisely understand the impact of alternative policies through the practice of counterfactual simulations and exercises. As a result, IO specialists play a key role in determining policy in many domains.

As an advanced graduate field seminar, this course is designed to fuel the transformation of graduate students into practitioners. This is done in three ways: First (and foremost) by immersing students in the literature, starting with formative work in the field, both theoretical and empirical, and progressing to the cutting edge. Students practice learning-by-doing and work with each other to reproduce several classic results. Second, students critique the work of others in the field by writing reports on current working papers, and develop their presentation skills by discussing important applied work. Finally, students generate proposals for future work in the field with an eye toward the third year paper requirement of Oregon's PhD program in economics.
:::
::::
